random_state: 34
seed: 12
###################################################################
dataset:
  unprocessed:
    train: 'split/train.csv'
    val: 'split/val.csv'
    train_val: 'split/train_val.csv'
    test: 'split/test.csv'

  sampled:
    dir: 'processed_data/sampled'
    rus:
      dir: 'processed_data/sampled/rus'
      train:
        dir: 'processed_data/sampled/rus/train'
        data: 'processed_data/sampled/rus/train/train.npz'
        metadata: 'processed_data/sampled/rus/train/train.json'
      train_val:
        dir: 'processed_data/sampled/rus/train_val'
        data: 'processed_data/sampled/rus/train_val/train_val.npz'
        metadata: 'processed_data/sampled/rus/train_val/train_val.json'

    enn:
      dir: 'processed_data/sampled/enn'
      train:
        dir: 'processed_data/sampled/enn/train'
        data: 'processed_data/sampled/enn/train/train.npz'
        metadata: 'processed_data/sampled/enn/train/train.json'
      train_val:
        dir: 'processed_data/sampled/enn/train_val'
        data: 'processed_data/sampled/enn/train_val/train_val.npz'
        metadata: 'processed_data/sampled/enn/train_val/train_val.json'

    smote:
      dir: 'processed_data/sampled/smote'
      train:
        dir: 'processed_data/sampled/smote/train'
        data: 'processed_data/sampled/smote/train/train.npz'
        metadata: 'processed_data/sampled/smote/train/train.json'
      train_val:
        dir: 'processed_data/sampled/smote/train_val'
        data: 'processed_data/sampled/smote/train_val/train_val.npz'
        metadata: 'processed_data/sampled/smote/train_val/train_val.json'

    smoteenn:
      dir: 'processed_data/sampled/smoteenn'
      train:
        dir: 'processed_data/sampled/smoteenn/train'
        data: 'processed_data/sampled/smoteenn/train/train.npz'
        metadata: 'processed_data/sampled/smoteenn/train/train.json'
      train_val:
        dir: 'processed_data/sampled/smoteenn/train_val'
        data: 'processed_data/sampled/smoteenn/train_val/train_val.npz'
        metadata: 'processed_data/sampled/smoteenn/train_val/train_val.json'

    smotetomek:
      dir: 'processed_data/sampled/smotetomek'
      train:
        dir: 'processed_data/sampled/smotetomek/train'
        data: 'processed_data/sampled/smotetomek/train/train.npz'
        metadata: 'processed_data/sampled/smotetomek/train/train.json'
      train_val:
        dir: 'processed_data/sampled/smotetomek/train_val'
        data: 'processed_data/sampled/smotetomek/train_val/train_val.npz'
        metadata: 'processed_data/sampled/smotetomek/train_val/train_val.json'



###################################################################
preprocessing:
  scaler: ['standard', 'robust']

###################################################################
features:
  target: 'Class'
  log_trans: ['Amount']
  construct: ['Time', 'Amount']
  numeric: ['Amount','Time', 'V1', 'V2', 'V3', 'V4', 'V5',
                    'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
                    'V12', 'V13', 'V14', 'V15', 'V16',
                    'V17', 'V18', 'V19', 'V20', 'V21',
                    'V22', 'V23', 'V24', 'V25', 'V26',
                    'V27', 'V28','hour', 'minute','second']

###################################################################
sampling:
  techniques:
    - 'rus'
    - 'enn'
    - 'smote'
    - 'smoteenn'
    - 'smotetomek'
  params:
    sampling_strategy: 'auto'
    smote_kn: 5
    enn_nn: 3

###################################################################
models:
  dir: 'models'

  logistic_regression:
    dir: 'models/lr'
    sample:
      none:
        dir: 'models/lr/none'
        model: 'models/lr/none/model.pkl'
        metadata: 'models/lr/none/model_params.json'
        eval: 'models/lr/none/model_eval_scores.json'
      rus:
        dir: 'models/lr/rus'
        model: 'models/lr/rus/model.pkl'
        metadata: 'models/lr/rus/model_params.json'
        eval: 'models/lr/rus/model_eval_scores.json'
      enn:
        dir: 'models/lr/enn'
        model: 'models/lr/enn/model.pkl'
        metadata: 'models/lr/enn/model_params.json'
        eval: 'models/lr/enn/model_eval_scores.json'
      smote:
        dir: 'models/lr/smote'
        model: 'models/lr/smote/model.pkl'
        metadata: 'models/lr/smote/model_params.json'
        eval: 'models/lr/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/lr/smoteenn'
        model: 'models/lr/smoteenn/model.pkl'
        metadata: 'models/lr/smoteenn/model_params.json'
        eval: 'models/lr/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/lr/smotetomek'
        model: 'models/lr/smotetomek/model.pkl'
        metadata: 'models/lr/smotetomek/model_params.json'
        eval: 'models/lr/smotetomek/model_eval_scores.json'

    params:
      solver: ['lbfgs', 'newton-cg', 'liblinear']
      max_iter: [100, 500, 800, 1000, 2000]
      class_weight: ['balanced', {1: 5, 0: 1}, {1: 10, 0: 1}, {1: 20, 0: 1}]
      lamda: [0.01, 0.1, 1, 10]


  random_forest:
    dir: 'models/rf'
    sample:
      none:
        dir: 'models/rf/none'
        model: 'models/rf/none/model.pkl'
        metadata: 'models/rf/none/model_params.json'
        eval: 'models/rf/none/model_eval_scores.json'
      rus:
        dir: 'models/rf/rus'
        model: 'models/rf/rus/model.pkl'
        metadata: 'models/rf/rus/model_params.json'
        eval: 'models/rf/rus/model_eval_scores.json'
      enn:
        dir: 'models/rf/enn'
        model: 'models/rf/enn/model.pkl'
        metadata: 'models/rf/enn/model_params.json'
        eval: 'models/rf/enn/model_eval_scores.json'
      smote:
        dir: 'models/rf/smote'
        model: 'models/rf/smote/model.pkl'
        metadata: 'models/rf/smote/model_params.json'
        eval: 'models/rf/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/rf/smoteenn'
        model: 'models/rf/smoteenn/model.pkl'
        metadata: 'models/rf/smoteenn/model_params.json'
        eval: 'models/rf/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/rf/smotetomek'
        model: 'models/rf/smotetomek/model.pkl'
        metadata: 'models/rf/smotetomek/model_params.json'
        eval: 'models/rf/smotetomek/model_eval_scores.json'

    n_iter: 25
    params:
      max_depth: [15, 20, 25]
      max_features: ['sqrt']
      n_estimators: [300, 400, 600]
      min_samples_leaf: [2, 5]
      class_weight: ['balanced', {1: 5, 0: 1}, {1: 10, 0: 1}, {1: 20, 0: 1}]

  neural_network:
    dir: 'models/nn'
    sample:
      none:
        dir: 'models/nn/none'
        model: 'models/nn/none/model.pkl'
        metadata: 'models/nn/none/model_params.json'
        eval: 'models/nn/none/model_eval_scores.json'
      rus:
        dir: 'models/nn/rus'
        model: 'models/nn/rus/model.pkl'
        metadata: 'models/nn/rus/model_params.json'
        eval: 'models/nn/rus/model_eval_scores.json'
      enn:
        dir: 'models/nn/enn'
        model: 'models/nn/enn/model.pkl'
        metadata: 'models/nn/enn/model_params.json'
        eval: 'models/nn/enn/model_eval_scores.json'
      smote:
        dir: 'models/nn/smote'
        model: 'models/nn/smote/model.pkl'
        metadata: 'models/nn/smote/model_params.json'
        eval: 'models/nn/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/nn/smoteenn'
        model: 'models/nn/smoteenn/model.pkl'
        metadata: 'models/nn/smoteenn/model_params.json'
        eval: 'models/nn/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/nn/smotetomek'
        model: 'models/nn/smotetomek/model.pkl'
        metadata: 'models/nn/smotetomek/model_params.json'
        eval: 'models/nn/smotetomek/model_eval_scores.json'

    n_iter: 30
    params:
      hidden_layers:
      - [32]
      - [64]
      - [64, 32]
      - [128, 64]
      - [128, 64, 32]
      activation: ['relu', 'tanh']
      alpha: [0.001, 0.01, 0.1]
      batch_size: [32, 64, 128]
      max_iter: [200, 400, 800]

  neural_network_fl:
    dir: 'models/nn-fl'
    sample:
      none:
        dir: 'models/nn-fl/none'
        model: 'models/nn-fl/none/model.pkl'
        scaler: 'model/nn-fl/none/model.pkl'
        metadata: 'models/nn-fl/none/model_params.json'
        eval: 'models/nn-fl/none/model_eval_scores.json'
      rus:
        dir: 'models/nn-fl/rus'
        model: 'models/nn-fl/rus/model.pkl'
        metadata: 'models/nn-fl/rus/model_params.json'
        eval: 'models/nn-fl/rus/model_eval_scores.json'
      enn:
        dir: 'models/nn-fl/enn'
        model: 'models/nn-fl/enn/model.pkl'
        metadata: 'models/nn-fl/enn/model_params.json'
        eval: 'models/nn-fl/enn/model_eval_scores.json'
      smote:
        dir: 'models/nn-fl/smote'
        model: 'models/nn-fl/smote/model.pkl'
        metadata: 'models/nn-fl/smote/model_params.json'
        eval: 'models/nn-fl/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/nn-fl/smoteenn'
        model: 'models/nn-fl/smoteenn/model.pkl'
        metadata: 'models/nn-fl/smoteenn/model_params.json'
        eval: 'models/nn-fl/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/nn-fl/smotetomek'
        model: 'models/nn-fl/smotetomek/model.pkl'
        metadata: 'models/nn-fl/smotetomek/model_params.json'
        eval: 'models/nn-fl/smotetomek/model_eval_scores.json'

    params:
      alpha: [0.25, 0.5, 0.75]
      gamma: [2.0, 3.0]
      hidden_layers:
      - [32]
      - [64, 32]
      - [128, 32]
      - [128, 64, 32]
      epochs : [50, 100, 200]
      patience: 30
      optimizer:
        lr: [0.001]
        weight_decay: [0.001, 0.0001]

  knn_classifier:
    dir: 'models/knn'
    sample:
      none:
        dir: 'models/knn/none'
        model: 'models/knn/none/model.pkl'
        metadata: 'models/knn/none/model_params.json'
        eval: 'models/knn/none/model_eval_scores.json'
      rus:
        dir: 'models/knn/rus'
        model: 'models/knn/rus/model.pkl'
        metadata: 'models/knn/rus/model_params.json'
        eval: 'models/knn/rus/model_eval_scores.json'
      enn:
        dir: 'models/knn/enn'
        model: 'models/knn/enn/model.pkl'
        metadata: 'models/knn/enn/model_params.json'
        eval: 'models/knn/enn/model_eval_scores.json'
      smote:
        dir: 'models/knn/smote'
        model: 'models/knn/smote/model.pkl'
        metadata: 'models/knn/smote/model_params.json'
        eval: 'models/knn/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/knn/smoteenn'
        model: 'models/knn/smoteenn/model.pkl'
        metadata: 'models/knn/smoteenn/model_params.json'
        eval: 'models/knn/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/knn/smotetomek'
        model: 'models/knn/smotetomek/model.pkl'
        metadata: 'models/knn/smotetomek/model_params.json'
        eval: 'models/knn/smotetomek/model_eval_scores.json'

    params:
      k: [3, 5, 7, 9]
      weights: ['uniform', 'distance']
      metric: ['manhattan', 'euclidean', 'minkowski']



  voting_classifier_1:
    dir: 'models/voting_1'
    sample:
      none:
        dir: 'models/voting_1/none'
        model: 'models/voting_1/none/model.pkl'
        metadata: 'models/voting_1/none/model_params.json'
        eval: 'models/voting_1/none/model_eval_scores.json'
      rus:
        dir: 'models/voting_1/rus'
        model: 'models/voting_1/rus/model.pkl'
        metadata: 'models/voting_1/rus/model_params.json'
        eval: 'models/voting_1/rus/model_eval_scores.json'
      enn:
        dir: 'models/voting_1/enn'
        model: 'models/voting_1/enn/model.pkl'
        metadata: 'models/voting_1/enn/model_params.json'
        eval: 'models/voting_1/enn/model_eval_scores.json'
      smote:
        dir: 'models/voting_1/smote'
        model: 'models/voting_1/smote/model.pkl'
        metadata: 'models/voting_1/smote/model_params.json'
        eval: 'models/voting_1/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/voting_1/smoteenn'
        model: 'models/voting_1/smoteenn/model.pkl'
        metadata: 'models/voting_1/smoteenn/model_params.json'
        eval: 'models/voting_1/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/voting_1/smotetomek'
        model: 'models/voting_1/smotetomek/model.pkl'
        metadata: 'models/voting_1/smotetomek/model_params.json'
        eval: 'models/voting_1/smotetomek/model_eval_scores.json'

    params:
      weights: [
                 [2,1,1],
                 [1,2,1],
                 [2,2,1]
      ]


  voting_classifier_2:
    dir: 'models/voting_2'
    sample:
      none:
        dir: 'models/voting_2/none'
        model: 'models/voting_2/none/model.pkl'
        metadata: 'models/voting_2/none/model_params.json'
        eval: 'models/voting_2/none/model_eval_scores.json'
      rus:
        dir: 'models/voting_2/rus'
        model: 'models/voting_2/rus/model.pkl'
        metadata: 'models/voting_2/rus/model_params.json'
        eval: 'models/voting_2/rus/model_eval_scores.json'
      enn:
        dir: 'models/voting_2/enn'
        model: 'models/voting_2/enn/model.pkl'
        metadata: 'models/voting_2/enn/model_params.json'
        eval: 'models/voting_2/enn/model_eval_scores.json'
      smote:
        dir: 'models/voting_2/smote'
        model: 'models/voting_2/smote/model.pkl'
        metadata: 'models/voting_2/smote/model_params.json'
        eval: 'models/voting_2/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/voting_2/smoteenn'
        model: 'models/voting_2/smoteenn/model.pkl'
        metadata: 'models/voting_2/smoteenn/model_params.json'
        eval: 'models/voting_2/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/voting_2/smotetomek'
        model: 'models/voting_2/smotetomek/model.pkl'
        metadata: 'models/voting_2/smotetomek/model_params.json'
        eval: 'models/voting_2/smotetomek/model_eval_scores.json'

    params:
      weights: [
                 [2,1,1],
                 [1,2,1],
                 [2,2,1]
      ]


  voting_classifier_3:
    dir: 'models/voting_3'
    sample:
      none:
        dir: 'models/voting_3/none'
        model: 'models/voting_3/none/model.pkl'
        metadata: 'models/voting_3/none/model_params.json'
        eval: 'models/voting_3/none/model_eval_scores.json'
      rus:
        dir: 'models/voting_3/rus'
        model: 'models/voting_3/rus/model.pkl'
        metadata: 'models/voting_3/rus/model_params.json'
        eval: 'models/voting_3/rus/model_eval_scores.json'
      enn:
        dir: 'models/voting_3/enn'
        model: 'models/voting_3/enn/model.pkl'
        metadata: 'models/voting_3/enn/model_params.json'
        eval: 'models/voting_3/enn/model_eval_scores.json'
      smote:
        dir: 'models/voting_3/smote'
        model: 'models/voting_3/smote/model.pkl'
        metadata: 'models/voting_3/smote/model_params.json'
        eval: 'models/voting_3/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/voting_3/smoteenn'
        model: 'models/voting_3/smoteenn/model.pkl'
        metadata: 'models/voting_3/smoteenn/model_params.json'
        eval: 'models/voting_3/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/voting_3/smotetomek'
        model: 'models/voting_3/smotetomek/model.pkl'
        metadata: 'models/voting_3/smotetomek/model_params.json'
        eval: 'models/voting_3/smotetomek/model_eval_scores.json'

    params:
      weights: [
                 [2,1,1,1],
                 [2,2,1,1],
                 [2,2,1,2],
                 [3,2,1,2],
                 [3,3,1,2]
      ]


  best_model:
    dir: 'best_model'
    model: 'best_model/best_model.pkl'
    eval: 'best_model/best_model_test_score.json'
    metadata: 'best_model/best_model_metadata.json'

###################################################################
evaluation:
  dir: 'docs/evaluation'
  scoring: 'average_precision'
  beta: 2
  cv_folds: 5

###################################################################
