random_state: 34
###################################################################
dataset:
  unprocessed:
    train: 'split/train.csv'
    val: 'split/val.csv'
    train_val: 'split/trainval.csv'
    test: 'split/test.csv'

  prepared:
    dir: 'processed_data/prepared'
    train:
      dir: 'processed_data/prepared/train'
      data: 'processed_data/prepared/train/train.npz'
      metadata: 'processed_data/prepared/train/train_metadata.json'
    val:
      dir: 'processed_data/prepared/val'
      data: 'processed_data/prepared/val/val.npz'
      metadata: 'processed_data/prepared/val/val_metadata.json'
    train_val:
      dir: 'processed_data/prepared/train+val'
      data: 'processed_data/prepared/train+val/train+val.npz'
      metadata: 'processed_data/prepared/train+val/train+val_metadata.json'
    test:
      dir: 'processed_data/prepared/test'
      data: 'processed_data/prepared/test/test.npz'
      metadata: 'processed_data/prepared/test/test_metadata.json'

  sampled:
    dir: 'processed_data/sampled'
    rus:
      dir: 'processed_data/sampled/rus'
      train: 'processed_data/sampled/rus/train.npz'
      train_metadata: 'processed_data/sampled/rus/train_metadata.json'
      train_val: 'processed_data/sampled/rus/train+val.npz'
      train_val_metadata: 'processed_data/sampled/rus/train+val_metadata.json'
    enn:
      dir: 'processed_data/sampled/enn'
      train: 'processed_data/sampled/enn/train.npz'
      train_metadata: 'processed_data/sampled/enn/train_metadata.json'
      train_val: 'processed_data/sampled/enn/train+val.npz'
      train_val_metadata: 'processed_data/sampled/enn/train+val_metadata.json'
    smote:
      dir: 'processed_data/sampled/smote'
      train: 'processed_data/sampled/smote/train.npz'
      train_metadata: 'processed_data/sampled/smote/train_metadata.json'
      train_val: 'processed_data/sampled/smote/train+val.nzp'
      train_val_metadata: 'processed_data/sampled/smote/train+val_metadata.json'
    smoteenn:
      dir: 'processed_data/sampled/smoteenn'
      train: 'processed_data/sampled/smoteenn/train.npz'
      train_metadata: 'processed_data/sampled/smoteenn/train_metadata.json'
      train_val: 'processed_data/sampled/smoteenn/train+val.npz'
      train_val_metadata: 'processed_data/sampled/smoteenn/train+val_metadata.json'
    smotetomek:
      dir: 'processed_data/sampled/smotetomek'
      train: 'processed_data/sampled/smotetomek/train.npz'
      train_metadata: 'processed_data/sampled/smotetomek/train_metadata.json'
      train_val: 'processed_data/sampled/smotetomek/train+val.npz'
      train_val_metadata: 'processed_data/sampled/smotetomek/train+val_metadata.json'



###################################################################
preprocessing:
  scaler: ['standard', 'robust']

###################################################################
features:
  target: 'Class'
  log_trans: ['Amount']
  numeric: ['Amount','Time', 'V1', 'V2', 'V3', 'V4', 'V5',
                    'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
                    'V12', 'V13', 'V14', 'V15', 'V16',
                    'V17', 'V18', 'V19', 'V20', 'V21',
                    'V22', 'V23', 'V24', 'V25', 'V26',
                    'V27', 'V28','hour', 'minute','second']

###################################################################
sampling:
  techniques:
    - 'rus'
    - 'enn'
    - 'smote'
    - 'smoteenn'
    - 'smotetomek'
  params:
    sampling_strategy: 'auto'
    smote_kn: 5
    enn_nn: 3

###################################################################
models:
  dir: 'models'

  logistic_regression:
    dir: 'models/lr'
    sample:
      none:
        dir: 'models/lr/none'
        model: 'models/lr/none/model.pkl'
        metadata: 'models/lr/none/model_params.json'
        eval: 'models/lr/none/model_eval_scores.json'
      rus:
        dir: 'models/lr/rus'
        model: 'models/lr/rus/model.pkl'
        metadata: 'models/lr/rus/model_params.json'
        eval: 'models/lr/rus/model_eval_scores.json'
      enn:
        dir: 'models/lr/enn'
        model: 'models/lr/enn/model.pkl'
        metadata: 'models/lr/enn/model_params.json'
        eval: 'models/lr/enn/model_eval_scores.json'
      smote:
        dir: 'models/lr/smote'
        model: 'models/lr/smote/model.pkl'
        metadata: 'models/lr/smote/model_params.json'
        eval: 'models/lr/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/lr/smoteenn'
        model: 'models/lr/smoteenn/model.pkl'
        metadata: 'models/lr/smoteenn/model_params.json'
        eval: 'models/lr/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/lr/smotetomek'
        model: 'models/lr/smotetomek/model.pkl'
        metadata: 'models/lr/smotetomek/model_params.json'
        eval: 'models/lr/smotetomek/model_eval_scores.json'

    params:
      solver: ['lbfgs', 'newton-cg', 'liblinear']
      max_iter: [100, 500, 800, 1000, 2000]
      class_weight: ['balanced', {1: 5, 0: 1}, {1: 10, 0: 1}, {1: 20, 0: 1}]


  random_forest:
    dir: 'models/rf'
    sample:
      none:
        dir: 'models/rf/none'
        model: 'models/rf/none/model.pkl'
        metadata: 'models/rf/none/model_params.json'
        eval: 'models/rf/none/model_eval_scores.json'
      rus:
        dir: 'models/rf/rus'
        model: 'models/rf/rus/model.pkl'
        metadata: 'models/rf/rus/model_params.json'
        eval: 'models/rf/rus/model_eval_scores.json'
      enn:
        dir: 'models/rf/enn'
        model: 'models/rf/enn/model.pkl'
        metadata: 'models/rf/enn/model_params.json'
        eval: 'models/rf/enn/model_eval_scores.json'
      smote:
        dir: 'models/rf/smote'
        model: 'models/rf/smote/model.pkl'
        metadata: 'models/rf/smote/model_params.json'
        eval: 'models/rf/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/rf/smoteenn'
        model: 'models/rf/smoteenn/model.pkl'
        metadata: 'models/rf/smoteenn/model_params.json'
        eval: 'models/rf/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/rf/smotetomek'
        model: 'models/rf/smotetomek/model.pkl'
        metadata: 'models/rf/smotetomek/model_params.json'
        eval: 'models/rf/smotetomek/model_eval_scores.json'

    n_iter: 25
    params:
      max_depth: [15, 20, 25]
      max_features: ['sqrt']
      n_estimators: [300, 400, 600]
      min_samples_leaf: [2, 5]
      class_weight: ['balanced', {1: 5, 0: 1}, {1: 10, 0: 1}, {1: 20, 0: 1}]

  neural_network:
    dir: 'models/nn'
    sample:
      none:
        dir: 'models/nn/none'
        model: 'models/nn/none/model.pkl'
        metadata: 'models/nn/none/model_params.json'
        eval: 'models/nn/none/model_eval_scores.json'
      rus:
        dir: 'models/nn/rus'
        model: 'models/nn/rus/model.pkl'
        metadata: 'models/nn/rus/model_params.json'
        eval: 'models/nn/rus/model_eval_scores.json'
      enn:
        dir: 'models/nn/enn'
        model: 'models/nn/enn/model.pkl'
        metadata: 'models/nn/enn/model_params.json'
        eval: 'models/nn/enn/model_eval_scores.json'
      smote:
        dir: 'models/nn/smote'
        model: 'models/nn/smote/model.pkl'
        metadata: 'models/nn/smote/model_params.json'
        eval: 'models/nn/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/nn/smoteenn'
        model: 'models/nn/smoteenn/model.pkl'
        metadata: 'models/nn/smoteenn/model_params.json'
        eval: 'models/nn/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/nn/smotetomek'
        model: 'models/nn/smotetomek/model.pkl'
        metadata: 'models/nn/smotetomek/model_params.json'
        eval: 'models/nn/smotetomek/model_eval_scores.json'

    n_iter: 30
    params:
      hidden_layers:
      - [32]
      - [64]
      - [64, 32]
      - [128, 64]
      - [128, 64, 32]
      activation: ['relu', 'tanh']
      alpha: [0.001, 0.01, 0.1]
      batch_size: [32, 64, 128]
      learning_rate: [0.001, 0.01]
      max_iter: [200, 400]

  voting_classifier:
    dir: 'models/voting'
    sample:
      none:
        dir: 'models/voting/none'
        model: 'models/voting/none/model.pkl'
        metadata: 'models/voting/none/model_params.json'
        eval: 'models/voting/none/model_eval_scores.json'
      rus:
        dir: 'models/voting/rus'
        model: 'models/voting/rus/model.pkl'
        metadata: 'models/voting/rus/model_params.json'
        eval: 'models/voting/rus/model_eval_scores.json'
      enn:
        dir: 'models/voting/enn'
        model: 'models/voting/enn/model.pkl'
        metadata: 'models/voting/enn/model_params.json'
        eval: 'models/voting/enn/model_eval_scores.json'
      smote:
        dir: 'models/voting/smote'
        model: 'models/voting/smote/model.pkl'
        metadata: 'models/voting/smote/model_params.json'
        eval: 'models/voting/smote/model_eval_scores.json'
      smoteenn:
        dir: 'models/voting/smoteenn'
        model: 'models/voting/smoteenn/model.pkl'
        metadata: 'models/voting/smoteenn/model_params.json'
        eval: 'models/voting/smoteenn/model_eval_scores.json'
      smotetomek:
        dir: 'models/voting/smotetomek'
        model: 'models/voting/smotetomek/model.pkl'
        metadata: 'models/voting/smotetomek/model_params.json'
        eval: 'models/voting/smotetomek/model_eval_scores.json'

    params:
      voting: 'soft'
      estimators: ['lr','rf', 'nn']
      weights: [[1, 1, 1], [1, 2, 3], [1, 3, 2]]


###################################################################
evaluation:
  scoring: 'average_precision'
  beta: 2
  cv_folds: 5

###################################################################
