random_state: 34
###################################################################
dataset:
  unprocessed:
    train: 'split/train.csv'
    val: 'split/val.csv'
    train_val: 'split/trainval.csv'
    test: 'split/test.csv'

  prepared:
    dir: 'processed_data/prepared'
    train: 'processed_data/prepared/train.npz'
    train_metadata: 'processed_data/prepared/train_metadata.json'
    val: 'processed_data/prepared/val.npz'
    val_metadata: 'processed_data/prepared/val_metadata.json'
    train_val:  'processed_data/prepared/train+val.npz'
    train_val_metadata: 'processed_data/prepared/train+val_metadata.json'
    test:  'processed_data/prepared/test.npz'
    test_metadata: 'processed_data/prepared/test_metadata.json'

  sampled:
    dir: 'processed_data/sampled'
    train: 'processed_data/sampled/train'
    train_metadata: 'processed_data/sampled/train_metadata'
    train_val: 'processed_data/sampled/train+val'
    train_val_metadata: 'processed_data/sampled/train+val_metadata'

###################################################################
preprocessing:
  scaler: 'standard'

###################################################################
features:
  target: 'Class'
  log_trans: ['Amount']
  numeric: ['Time', 'V1', 'V2', 'V3', 'V4', 'V5',
                    'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
                    'V12', 'V13', 'V14', 'V15', 'V16',
                    'V17', 'V18', 'V19', 'V20', 'V21',
                    'V22', 'V23', 'V24', 'V25', 'V26',
                    'V27', 'V28', 'hour', 'minute','second']

###################################################################
sampling:
  techniques:
    - 'rus'
    - 'enn'
    - 'smote'
    - 'smoteenn'
    - 'smotetomek'
  params:
    sampling_strategy: 'auto'
    smote_kn: 5
    enn_nn: 3

###################################################################
models:
  dir: 'models'

  logistic_regression:
    dir: 'models/lr'
    model: 'models/lr/lr_model.pkl'
    metadata: 'models/lr/lr_model.json'
    params:
      solver: ['lbfgs', 'newton-cg', 'liblinear']
      max_iter: [100, 500, 800, 1000, 2000]
      class_weight: [0.2, 0.5, 0.8, 1]


  random_forest:
    dir: 'models/rf'
    model: 'models/rf/rf_model.pkl'
    metadata: 'models/rf/rf_model.json'
    n_iter: 25
    params:
      max_depth: [15, 20, 25]
      max_features: ['sqrt']
      n_estimators: [300, 400, 600]
      min_samples_leaf: [2, 5]
      class_weight: [0.5, 0.8, 1]

  voting_classifier:
    dir: 'models/voting'
    model: 'models/voting/vc_model.pkl'
    metadata: 'models/voting/vc_model.json'
    params:
      voting: 'soft'
      estimators: ['lr','rf']
      weights: [1.5, 2]


###################################################################
evaluation:
  scoring: 'average_precision'
  beta: 2
  cv_folds: 5

###################################################################
